apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-app
        image: localhost:5000/cluster-cp2-fiap:v1 
        ports:
        - containerPort: 80
        command: ["python"]
        args: ["./app.py"]
      imagePullSecrets:  
      - name: dockerhub-secret  
